version: '3.9'
name: e-commerce

volumes:
  e-commerce-database-volume:
    name: e-commerce-database-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/e-commerce/data/
  e-commerce-mongodb-volume:
    name: e-commerce-mongodb-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/e-commerce/mongodb/

networks:
  e-commerce-network:
    driver: bridge

services:
  e-commerce.api:
    container_name: e-commerce.api
    image: ${DOCKER_REGISTRY-}ecommerceapi
    build:
      context: .
      dockerfile: src/E-commerce.API/Dockerfile
    depends_on:
      e-commerce.database:
        condition: service_started
      e-commerce.azurite:
        condition: service_started
      e-commerce.mongoDb:
        condition: service_started
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - e-commerce-network
    environment:
      - ASPNETCORE_URLS=https://+:8000;http://+:8001
      - AzureStorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;
  e-commerce.database:
    container_name: e-commerce.database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "Password123$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - e-commerce-database-volume:/var/opt/mssql/data
    networks:
      - e-commerce-network
  e-commerce.azurite:
    container_name: e-commerce.azurite
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --skipApiVersionCheck --location /workspace"
    ports:
      - "10000:10000"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    volumes:
      - D:/e-commerce/azurite:/workspace
    networks:
      - e-commerce-network
  e-commerce.mongoDb:
    container_name: e-commerce.mongoDb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password#2
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    volumes:
      - e-commerce-mongodb-volume:/data/db
    networks:
      - e-commerce-network